### ISSUE TITLE
Broken on macOS

### ISSUE THREAD

**Issue by scorsi** [tlhunter/mig#16]
Hi,

Initially I thought your tool were broken but there's just a name conflicts : `mig` is a cli already in use on macOS. It took me a long time to realise this :) 

I had to rename your tool `migrator`, still, I am not able to run your tool, every command, either returns nothing nor `usage: mig <command>`.
Tried:
```
❯ MIG_CREDENTIALS=X migrator init

❯ migrator --credentials=X init
usage: mig <command>

❯ migrator init --credentials=X
usage: mig <command>

❯ MIG_CREDENTIALS=X migrator create create_user

```

`version` command works:
```
❯ migrator version
mig version: 0.4.0
build time:  2023-02-21T01:24:23+0000
```

**Comment by tlhunter** [comment]
Looks like you're right, `mig` is some CLI tools binary on macOS:

```
$ mig
xcrun: error: invalid active developer path 
  (/Library/Developer/CommandLineTools), missing xcrun at:
  /Library/Developer/CommandLineTools/usr/bin/xcrun
```

And yeah, it looks like the commands, other than `version`, fail silently. It even exits with a 0 status code.
